#!/usr/bin/env bash

set -euo pipefail

if [ "$#" != "1" ]; then
  echo "usage: $0 <path/to/release>"
  exit 1
fi

release=$1

grep -REhv '\s+#\s+' "${release}/jobs" |
  grep -Eoh 'env(_file)?: (([A-Z0-9_])+|http_proxy|https_proxy|no_proxy)' |
  sed -e "s/^env\(_file\)\?: //"
