platform: linux

image_resource:
  type: registry-image
  source: { repository: concourse/unit }

inputs:
  - name: ci
  - name: version

outputs:
  - name: component-version

params:
  COMPONENT_NAME: ~
  CONCOURSE_VERSION:

run:
  path: ci/tasks/discover-component-version/run.sh
