---
platform: linux

image_resource:
  type: registry-image
  source: { repository: concourse/bash }

inputs:
  - name: ci

params:
  GITHUB_TOKEN:
  PRNUMBER:
  OWNER: concourse
  REPO: concourse

run:
  path: ci/tasks/validate-pr/run.sh
