FROM busybox

COPY bosh-io-release-resource/   /usr/local/concourse/resource-types/bosh-io-release/
COPY bosh-io-stemcell-resource/  /usr/local/concourse/resource-types/bosh-io-stemcell/
COPY docker-image-resource/      /usr/local/concourse/resource-types/docker-image/
COPY git-resource/               /usr/local/concourse/resource-types/git/
COPY github-release-resource/    /usr/local/concourse/resource-types/github-release/
COPY hg-resource/                /usr/local/concourse/resource-types/hg/
COPY mock-resource/              /usr/local/concourse/resource-types/mock/
COPY pool-resource/              /usr/local/concourse/resource-types/pool/
COPY registry-image-resource/    /usr/local/concourse/resource-types/registry-image/
COPY s3-resource/                /usr/local/concourse/resource-types/s3/
COPY semver-resource/            /usr/local/concourse/resource-types/semver/
COPY time-resource/              /usr/local/concourse/resource-types/time/
COPY tracker-resource/           /usr/local/concourse/resource-types/tracker/
