platform: linux

image_resource:
  type: registry-image
  source: { repository: concourse/unit }

inputs:
  - name: concourse
  - name: ci
  - name: dev-image
  - name: postgres-image

caches:
  - path: gopath
  - path: concourse/web/wats/node_modules

params:
  RUNTIME: guardian

run:
  path: ci/tasks/scripts/with-docker-compose
  args:
    - "ci/tasks/watsjs/run.sh"
    # remove --serial after dex serialization failure is fixed:
    # https://github.com/concourse/concourse/issues/3890
    - "--serial"
    - "test/smoke.js"
