---
platform: linux

image_resource:
  type: registry-image
  source: { repository: concourse/unit }

params:
  GCP_PROJECT:
  GCP_KEY:
  SSH_KEY:
  WORKSPACE: default
  # variables consumed by terraform and their default values
  TF_VAR_GCP_IMAGE: "ubuntu-2204-lts"
  TF_VAR_RUNTIME: "containerd"

inputs:
  - name: ci

run:
  path: ci/tasks/terraform-smoke/cleanup.sh
