---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ubuntu
    tag: noble

params:
  NORSK_PIPELINE:

inputs:
- name: ci
- name: scan-status

run:
  path: ci/tasks/scripts/check-norsk-status
