---
platform: linux

inputs:
- name: concourse
- name: ci
- name: final-version
  optional: true

outputs:
- name: fly-darwin

caches:
- path: gopath

params:
  GOOS: darwin

run:
  path: ci/tasks/scripts/fly-build
