---
platform: linux

image_resource:
  type: registry-image
  source: { repository: cgr.dev/chainguard/wolfi-base }

params:
  # VAR_*
  # e.g. VAR_foo=123, VAR_bar=[1,"2",3] --> {"foo": 123, "bar": [1, "2", 3]}
  EXPR:

outputs:
  - name: result

run:
  path: sh
  args:
    - -c
    - |
      set -euo pipefail
      apk add --no-progress jq
      env | \
        jq --raw-input --slurp 'split("\n") | .[] | select(startswith("VAR_")) | sub("^VAR_"; "")' | \
        jq '[capture( "(?<key>[^=]*)=(?<value>.*)" )] | from_entries | map_values(fromjson)' | \
        jq --slurp add | \
        jq "$EXPR" > result/result.json
