---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

inputs:
  - name: ci
  - name: concourse-chart

params:
  SERVICE_ACCOUNT_KEY:

run:
  path: ci/tasks/scripts/k8s-test
