---
platform: linux

image_resource:
  type: registry-image
  source: { repository: cgr.dev/chainguard/wolfi-base }

outputs:
  - name: date-tag

params:
  VERSION: ~

run:
  path: sh
  args:
    - -ce
    - |
      echo ${VERSION}-$(date +"%Y%m%d") > date-tag/tag
