---
platform: linux

image_resource:
  type: registry-image
  source: {repository: aquasec/trivy}

inputs:
- name: image
- name: ci

params:
  TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db

run:
  path: ci/tasks/scripts/trivy-scan
