---
platform: linux

inputs:
  - name: concourse
  - name: ci
  - name: version
  - name: final-version
    optional: true
  - name: dev-amd64
  - name: dev-arm64
  - name: resource-types-amd64
  - name: resource-types-arm64
  - name: fly-builds

caches:
  - path: gopath

outputs:
  - name: concourse-tarballs

run:
  path: ci/tasks/concourse-build/run.sh
