---
platform: linux

image_resource:
  type: registry-image
  source: { repository: concourse/unit }

inputs:
  - name: concourse
  - name: ci

caches:
  - path: concourse/node_modules

run:
  path: ci/tasks/yarn-benchmark/run.sh
