---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

inputs:
- name: ci

run:
  path: ci/tasks/helpers/start-docker
  args: [ci/tasks/docker-mounts/run.sh]
