---
platform: linux

params:
  DOCKERFILE: ci/tasks/build-golang-builder-image/Dockerfile
  CONTEXT: .
  IMAGE_PLATFORM: linux/arm64,linux/amd64
  OUTPUT_OCI: true

inputs:
  - name: ci
  - name: base-image
    optional: true

outputs:
  - name: image

caches:
  - path: cache

run:
  path: build
