---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/unit

inputs:
- name: concourse
- name: ci

caches:
- path: gopath
- path: concourse/web/wats/node_modules

params:
  ATC_URL:
  ATC_ADMIN_USERNAME: admin
  ATC_ADMIN_PASSWORD: admin
  ATC_GUEST_USERNAME: guest
  ATC_GUEST_PASSWORD: guest

run:
  path: ci/tasks/watsjs-smoke/run.sh
