---
platform: linux

image_resource:
  type: registry-image
  source: { repository: concourse/unit }

inputs:
  - name: ci
  - name: resource-type-versions

outputs:
  - name: built-notes

run:
  path: ci/tasks/build-release-notes/run.sh
