---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/dev}

inputs:
- name: concourse
- name: ci

caches:
- path: gopath

run:
  path: ci/tasks/scripts/containerd-integration
