---
platform: linux

image_resource:
  type: registry-image
  source: { repository: concourse/unit }

inputs:
  - name: version
  - name: linux-amd64-rc
  - name: linux-arm64-rc
  - name: windows-amd64-rc
  - name: darwin-amd64-rc
  - name: darwin-arm64-rc
  - name: ci

outputs:
  - name: concourse-linux
  - name: concourse-windows
  - name: concourse-darwin
  - name: fly-linux
  - name: fly-windows
  - name: fly-darwin

run:
  path: ci/tasks/prep-release-assets/run.sh
