---
platform: linux

image_resource:
  type: registry-image
  source: { repository: concourse/unit }

inputs:
  - name: concourse-chart
  - name: concourse-release
  - name: ci

outputs:
  - name: concourse-chart-bumped
    path: concourse-chart

run:
  path: ci/tasks/bump-chart-app-version/run.sh
