#@ load("@ytt:data", "data")
#@ load("@ytt:template", "template")
#@ load("@ytt:assert", "assert")

#@ resource_name = data.values.resource_name or assert.fail("resource name must be specified")
#@ def github_owner():
#@   if resource_name == "cf":
#@     return "cloudfoundry-community"
#@   end
#@  return "concourse"
#@ end

#@ def lts_string(str, lts):
  #@ if lts == True:
  #@ return str + "-lts"
  #@ else:
  #@ return str
  #@ end
#@ end


#@ def build_params(resource_name):
  #@ if resource_name == "registry-image":
CONTEXT: #@ resource_name + "-resource"
BUILD_ARG_DOCKER_PRIVATE_PASSWORD: ((registry_image_resource_docker.password))
BUILD_ARG_DOCKER_PRIVATE_REPO: ((registry_image_resource_docker.private_repo))
BUILD_ARG_DOCKER_PRIVATE_USERNAME: ((registry_image_resource_docker.username))

BUILD_ARG_DOCKER_PUSH_PASSWORD: ((registry_image_resource_docker.password))
BUILD_ARG_DOCKER_PUSH_REPO: ((registry_image_resource_docker.push_repo))
BUILD_ARG_DOCKER_PUSH_USERNAME: ((registry_image_resource_docker.username))

BUILD_ARG_GCR_PUSH_SERVICE_ACCOUNT_KEY: ((registry_image_resource_gcr.service_account_key))
BUILD_ARG_GCR_PUSH_REPO: ((registry_image_resource_gcr.repo))
  #@ elif resource_name == "docker-image":
CONTEXT: #@ resource_name + "-resource"
UNPACK_ROOTFS: 'true'
  #@ else:
CONTEXT: #@ resource_name + "-resource"
  #@ end
#@ end

#@ def build_task(resource_name, distro):
task: build
privileged: true
image: oci-build-task
config:
  platform: linux
  inputs:
  - name: #@ resource_name + "-resource"
  - name: #@ determine_base(distro)
  - name: golang-builder
  outputs:
  - name: built-resource-image
    path: image
  params:
    DOCKERFILE: #@ resource_name + "-resource/dockerfiles/" + distro + "/Dockerfile"
    ADDITIONAL_TARGETS: tests
    IMAGE_ARG_base_image: #@ determine_base(distro) + "/image.tar"
    IMAGE_ARG_builder_image: golang-builder/image.tar
    _: #@ template.replace(build_params(resource_name))
  run: {path: build}
#@ end

#@ def build_image(distro, lts):
name: #@ lts_string("build-" + distro, lts)
serial_groups: [build]
on_failure: &failed-ci
  put: notify
  params:
    mode: normal
    alert_type: failed
plan:
- in_parallel:
  - get: daily-trigger
    trigger: true
  - get: #@ resource_name + "-resource"
    resource: #@ lts_string("resource-repo", lts)
    trigger: true
  - get: #@ determine_base(distro)
    resource: #@ lts_string(determine_base(distro), lts)
    trigger: true
    params: {format: oci}
  - get: golang-builder
    trigger: true
    params: {format: oci}
  - get: oci-build-task
  - #@ template.replace(extra_get_steps(distro))
- #@ build_task(resource_name, distro)
- #@ template.replace(extra_steps(distro))
- put: #@ lts_string("resource-image-dev-" + distro, lts)
  params: {image: built-resource-image/image.tar}
#@ end

#@ def scan_task(distro):
task: #@ "scan-" + distro
image: trivy
config:
  platform: linux
  inputs:
  - name: #@ "resource-image-dev-" + distro
    path: image
  - name: trivy-db
  run:
    path: sh
    args:
    - -c
    - |
      mkdir db
      tar -xzf trivy-db/trivy-offline.db.tgz -C ./db

      trivy \
        --cache-dir $(pwd) \
        image \
        --severity "HIGH,CRITICAL" \
        --ignore-unfixed \
        --exit-code 1 \
        --input image/image.tar
on_failure:
  put: notify
  params:
    mode: normal
    channel: #@ determine_channel(distro)
    alert_type: failed
on_error:
  put: notify
  params:
    mode: normal
    channel: #@ determine_channel(distro)
    alert_type: failed
#@ end

#@ def scan_image(lts):
name: #@ lts_string("scan-image", lts)
plan:
- in_parallel:
  - get: resource-repo
    resource: #@ lts_string("resource-repo", lts)
    passed:
    - #@ lts_string("build-alpine", lts)
    - #@ lts_string("build-ubuntu", lts)
  - get: resource-image-dev-alpine
    resource: #@ lts_string("resource-image-dev-alpine", lts)
    passed:
    - #@ lts_string("build-alpine", lts)
    params: {format: oci}
    trigger: true
  - get: resource-image-dev-ubuntu
    resource: #@ lts_string("resource-image-dev-ubuntu", lts)
    passed:
    - #@ lts_string("build-ubuntu", lts)
    params: {format: oci}
    trigger: true
  - get: trivy
    trigger: true
  - get: trivy-db
    trigger: true
    params: {globs: [trivy-offline.db.tgz]}
- try:
    in_parallel:
      - #@ scan_task("alpine")
      - #@ scan_task("ubuntu")
#@ end

#@ def extra_steps(distro):
  #@ if resource_name == "docker-image":
- task: smoke-test
  image: built-resource-image
  file: docker-image-resource/ci/smoke-test.yml
  privileged: true
  params:
    REPOSITORY: busybox
  output_mapping:
    fetched-image: busybox
- task: use-fetched-image
  image: busybox
  config:
    platform: linux
    run:
      path: /bin/true
  #@ else: return []
#@ end

#@ def determine_base(distro):
#@ if distro == "alpine":
#@   return "alpine"
#@ elif distro == "ubuntu":
#@   return "ubuntu-bionic"
#@ end
#@ end

#@ def determine_channel(distro):
#@ if resource_name == "git" and distro == "alpine":
#@  return "concourse-interrupt"
#@ else: return ""
#@ end

#@ def validate_pr(distro):
name: #@ "prs-" + distro
public: true
serial: true
serial_groups:
- validate
plan:
- in_parallel:
  - get: resource-pr
    trigger: true
    version: every
  - get: #@ determine_base(distro)
    trigger: true
    params: {format: oci}
  - get: oci-build-task
  - get: golang-builder
    params: {format: oci}
  - #@ template.replace(extra_get_steps(distro))
- put: #@ resource_name + "-resource"
  resource: resource-pr
  params:
    context: #@ "status-" + distro
    path: resource-pr
    status: pending
- do:
  - #@ build_task(resource_name, distro)
  - #@ template.replace(extra_steps(distro))
  on_failure:
    put: resource-pr
    params:
      context: #@ "status-" + distro
      path: resource-pr
      status: failure
  on_success:
    put: resource-pr
    params:
      context: #@ "status-" + distro
      path: resource-pr
      status: success
#@ end


#@ def extra_get_steps(distro):
  #@ if resource_name == "cf":
- get: cf-cli
  trigger: true
  params: {globs: ["cf-cli*linux*"]}
  #@ else: return []
#@ end

#@ def publish_job(bump, lts):
name: #@ lts_string("publish-" + bump, lts)
plan:
- in_parallel:
  - get: resource-repo
    resource: #@ lts_string("resource-repo", lts)
    passed:
      - #@ lts_string("scan-image", lts)
  - get: ci
  - get: release-me
  - get: resource-image-dev-alpine
    resource: #@ lts_string("resource-image-dev-alpine", lts)
    passed:
      - #@ lts_string("scan-image", lts)
    params: {format: oci}
  - get: resource-image-dev-alpine-rootfs
    resource: #@ lts_string("resource-image-dev-alpine", lts)
    passed:
      - #@ lts_string("scan-image", lts)
    params: {format: rootfs}
  - get: resource-image-dev-ubuntu
    resource: #@ lts_string("resource-image-dev-ubuntu", lts)
    passed:
      - #@ lts_string("scan-image", lts)
    params: {format: oci}
  - get: resource-image-dev-ubuntu-rootfs
    resource: #@ lts_string("resource-image-dev-ubuntu", lts)
    passed:
      - #@ lts_string("scan-image", lts)
    params: {format: rootfs}
  - get: version
    resource: #@ lts_string("version", lts)
    params:
      bump: #@ bump
- task: create-release
  config:
    platform: linux
    image_resource:
      type: registry-image
      source:
        repository: ubuntu
    inputs:
    - name: version
    - name: resource-image-dev-alpine-rootfs
    - name: resource-image-dev-ubuntu-rootfs
    outputs:
    - name: release
    run:
      path: bash
      args:
      - "-exc"
      #@yaml/text-templated-strings
      - |
        cat <<EOF > resource_metadata.json
        {
          "type": "(@= resource_name @)",
          "version": "$(cat version/number)",
          "privileged": (@= str(privileged()).lower() @),
          "unique_version_history": (@= str(unique_version_history()).lower() @)
        }
        EOF

        version="$(cat version/number)"
        echo "v${version}" > release/name

        pushd resource-image-dev-alpine-rootfs
          cp ../resource_metadata.json .
          tar -czf rootfs.tgz -C rootfs .
          tar -czf ../release/(@= resource_name @)-resource-${version}-alpine.tgz rootfs.tgz resource_metadata.json
        popd

        pushd resource-image-dev-ubuntu-rootfs
          cp ../resource_metadata.json .
          tar -czf rootfs.tgz -C rootfs .
          tar -czf ../release/(@= resource_name @)-resource-${version}-ubuntu.tgz rootfs.tgz resource_metadata.json
        popd
- task: build-release-notes
  file: ci/tasks/build-release-notes.yml
  params:
    GITHUB_OWNER: #@ github_owner()
    GITHUB_REPO: #@ resource_name + "-resource"
    GITHUB_TOKEN: ((concourse_github_dummy.access_token))
    GITHUB_BRANCH: master
  input_mapping:
    repo: resource-repo
- task: generate-dpkg-list
  image: resource-image-dev-ubuntu-rootfs
  config:
    platform: linux
    inputs:
    - name: version
    outputs:
    - name: dpkg-file
    run:
      path: bash
      args:
      - "-exc"
      #@yaml/text-templated-strings
      - |
        VERSION="$(cat version/number)"
        RESOURCE="(@= resource_name @)"
        DPKG_FILE="${RESOURCE}-dpkg-list-${VERSION}.txt"
        dpkg -l > "dpkg-file/${DPKG_FILE}"
- load_var: version
  file: version/version
- in_parallel:
  - put: resource-image
    params:
      image: resource-image-dev-alpine/image.tar
      version: ((.:version))
      bump_aliases: true
  - put: resource-image-alpine
    params:
      image: resource-image-dev-alpine/image.tar
      version: ((.:version))
      bump_aliases: true
  - put: resource-image-ubuntu
    params:
      image: resource-image-dev-ubuntu/image.tar
      version: ((.:version))
      bump_aliases: true
  - put: resource-repo-release
    params:
      commitish: resource-repo/.git/ref
      body: built-notes/notes.md
      globs:
      - release/*.tgz
      name: release/name
      tag: version/version
      tag_prefix: v
- put: dpkg-list-store
  params:
    file: #@ "dpkg-file/" + resource_name + "-dpkg-list-*.txt"
- put: version
  resource: #@ lts_string("version", lts)
  params:
    file: version/version
#@ end

#@ def rebuild_images(distro):
name: #@ "republish-images-" + distro
on_failure: &failed-ci
  put: notify
  params:
    mode: normal
    alert_type: failed
plan:
- in_parallel:
  - get: daily-trigger
    trigger: true
  - get: #@ resource_name + "-resource"
    resource: resource-repo-tags
  - get: #@ determine_base(distro)
    trigger: true
    params: {format: oci}
  - get: golang-builder
    params: {format: oci}
  - get: oci-build-task
  - get: version
  - get: ci
  - #@ template.replace(extra_get_steps(distro))
- load_var: version
  file: version/version
- #@ build_task(resource_name, distro)
- #@ template.replace(extra_steps(distro))
- task: #@ distro + "-date-tag"
  image: oci-build-task
  file: ci/tasks/tag-version-with-date.yml
  params:
    VERSION: #@ "((.:version))-" + distro
- in_parallel:
  - put: #@ "resource-image-" + distro
    params:
      image: built-resource-image/image.tar
      version: ((.:version))
      bump_aliases: true
      additional_tags: date-tag/tag
  #@ if distro == "alpine":
  - put: resource-image
    params:
      image: built-resource-image/image.tar
      version: ((.:version))
      bump_aliases: true
  #@ end
#@ end

#@ def unique_version_history():
#@ return resource_name == "time"
#@ end

#@ def privileged():
#@ return resource_name == "docker-image"
#@ end

---
groups:
- name: main
  jobs:
  - prs-*[!s]
  - build-*[!s]
  - scan-*[!s]
  - publish-*[!s]
- name: republish
  jobs:
  - republish-*
- name: lts
  jobs:
  - build-*-lts
  - scan-*-lts
  - publish-*-lts

jobs:
- #@ build_image("alpine", False)
- #@ build_image("ubuntu", False)
- #@ build_image("alpine", True)
- #@ build_image("ubuntu", True)
- #@ scan_image(False)
- #@ scan_image(True)
- #@ validate_pr("alpine")
- #@ validate_pr("ubuntu")
- #@ publish_job("major", False)
- #@ publish_job("minor", False)
- #@ publish_job("patch", False)
- #@ publish_job("patch", True)
- #@ rebuild_images("alpine")
- #@ rebuild_images("ubuntu")

resource_types:
- name: pull-request
  type: registry-image
  check_every: 2m
  source:
    repository: teliaoss/github-pr-resource

- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource

- name: slack-notifier
  type: registry-image
  #! Switch back to mockersf/concourse-slack-notifier once
  #! https://github.com/mockersf/concourse-slack-notifier/pull/86 is merged
  source: {repository: aoldershaw/concourse-slack-notifier}

resources:
- name: alpine
  type: registry-image
  icon: docker
  source:
    repository: alpine
    tag: latest
    username: ((docker.username))
    password: ((docker.password))

- name: alpine-lts
  type: registry-image
  icon: docker
  source:
    repository: alpine
    tag: 3.14
    username: ((docker.username))
    password: ((docker.password))

- name: ubuntu-bionic
  type: registry-image
  icon: docker
  source:
    repository: ubuntu
    tag: bionic
    username: ((docker.username))
    password: ((docker.password))

- name: ubuntu-bionic-lts
  type: registry-image
  icon: docker
  source:
    repository: ubuntu
    tag: bionic
    username: ((docker.username))
    password: ((docker.password))

- name: golang-builder
  type: registry-image
  icon: docker
  source:
    repository: concourse/golang-builder
    variant: bionic
    username: ((docker.username))
    password: ((docker.password))

- name: trivy
  type: registry-image
  icon: docker
  source:
    repository: aquasec/trivy
    username: ((docker.username))
    password: ((docker.password))

- name: trivy-db
  type: github-release
  icon: database
  source:
    owner: aquasecurity
    repository: trivy-db
    access_token: ((concourse_github_dummy.access_token))

- name: resource-repo
  type: git
  icon: github
  source:
    branch: master
    private_key: ((concourse_bot_private_key))
    uri: #@ "git@github.com:concourse/" + resource_name + "-resource"

- name: resource-repo-lts
  type: git
  icon: github
  source:
    branch: release/6.7.x
    private_key: ((concourse_bot_private_key))
    uri: #@ "git@github.com:concourse/" + resource_name + "-resource"

- name: resource-repo-tags
  type: git
  icon: github
  source:
    branch: master
    private_key: ((concourse_bot_private_key))
    uri: #@ "git@github.com:concourse/" + resource_name + "-resource"
    tag_filter: "v*"

- name: resource-repo-release
  type: github-release
  icon: package-variant-closed
  source:
    access_token: ((concourse_bot_access_token))
    owner: #@ github_owner()
    repository: #@ resource_name + "-resource"

- name: version
  type: semver
  icon: tag
  source:
    branch: version
    driver: git
    file: version
    private_key: ((concourse_bot_private_key))
    uri: #@ "git@github.com:" + github_owner() + "/" + resource_name + "-resource"

- name: version-lts
  type: semver
  icon: tag
  source:
    branch: version-lts
    driver: git
    file: version
    private_key: ((concourse_bot_private_key))
    uri: #@ "git@github.com:" + github_owner() + "/" + resource_name + "-resource"

- name: resource-pr
  type: pull-request
  icon: source-pull
  check_every: 2m
  source:
    access_token: ((pull_requests_access_token))
    base_branch: master
    repository: #@ github_owner() + "/" + resource_name + "-resource"

- name: resource-image
  type: registry-image
  icon: docker
  source:
    repository: #@ "concourse/" + resource_name + "-resource"
    username: ((docker.username))
    password: ((docker.password))

- name: resource-image-alpine
  type: registry-image
  icon: docker
  source:
    repository: #@ "concourse/" + resource_name + "-resource"
    variant: alpine
    username: ((docker.username))
    password: ((docker.password))

- name: resource-image-ubuntu
  type: registry-image
  icon: docker
  source:
    repository: #@ "concourse/" + resource_name + "-resource"
    variant: ubuntu
    username: ((docker.username))
    password: ((docker.password))

- name: resource-image-dev-alpine
  type: registry-image
  icon: docker
  source:
    repository: #@ "concourse/" + resource_name + "-resource"
    tag: dev
    password: ((docker.password))
    username: ((docker.username))

- name: resource-image-dev-ubuntu
  type: registry-image
  icon: docker
  source:
    password: ((docker.password))
    repository: #@ "concourse/" + resource_name + "-resource"
    tag: dev-ubuntu
    username: ((docker.username))

- name: resource-image-dev-alpine-lts
  type: registry-image
  icon: docker
  source:
    repository: #@ "concourse/" + resource_name + "-resource"
    tag: dev-lts
    password: ((docker.password))
    username: ((docker.username))

- name: resource-image-dev-ubuntu-lts
  type: registry-image
  icon: docker
  source:
    password: ((docker.password))
    repository: #@ "concourse/" + resource_name + "-resource"
    tag: dev-ubuntu-lts
    username: ((docker.username))

- name: dpkg-list-store
  type: gcs
  source:
    bucket: concourse-ubuntu-dpkg-list
    json_key: ((concourse_dpkg_list_json_key))
    regexp: #@ resource_name + "-dpkg-list-(.*).txt"

- name: ci
  type: git
  icon: github
  source:
    uri: https://github.com/concourse/ci.git
    branch: master

- name: release-me
  type: github-release
  icon: package-down
  source:
    owner: clarafu
    repository: release-me
    access_token: ((concourse_github_dummy.access_token))

- name: oci-build-task
  type: registry-image
  icon: docker
  source:
    repository: vito/oci-build-task

- name: notify
  type: slack-notifier
  icon: slack
  source:
    url: ((slack_hook))
    username: ((basic_auth.username))
    password: ((basic_auth.password))
    concourse_url: https://ci.concourse-ci.org

- name: daily-trigger
  type: time
  source:
    start: 1AM
    stop: 2AM

#@ if resource_name == "cf":
- name: cf-cli
  type: s3
  source:
    bucket: cf-cli-releases
    regexp: "releases/v([\\d\\.]+)/cf-cli_.*_linux_x86-64.tgz"
    region_name: us-west-1
#@ end
