#@ load("@ytt:data", "data")
#@ load("@ytt:template", "template")
#@ load("@ytt:assert", "assert")

#@ resource_name = data.values.resource_name or assert.fail("resource name must be specified")
#@ def github_owner():
#@   if resource_name == "cf":
#@     return "cloudfoundry-community"
#@   end
#@  return "concourse"
#@ end

#@ def build_params(resource_name):
  #@ if resource_name == "registry-image":
CONTEXT: #@ resource_name + "-resource"
BUILD_ARG_DOCKER_PRIVATE_PASSWORD: ((registry_image_resource_docker.password))
BUILD_ARG_DOCKER_PRIVATE_REPO: ((registry_image_resource_docker.private_repo))
BUILD_ARG_DOCKER_PRIVATE_USERNAME: ((registry_image_resource_docker.username))

BUILD_ARG_DOCKER_PUSH_PASSWORD: ((registry_image_resource_docker.password))
BUILD_ARG_DOCKER_PUSH_REPO: ((registry_image_resource_docker.push_repo))
BUILD_ARG_DOCKER_PUSH_USERNAME: ((registry_image_resource_docker.username))

BUILD_ARG_GCR_PUSH_SERVICE_ACCOUNT_KEY: ((registry_image_resource_gcr.service_account_key))
BUILD_ARG_GCR_PUSH_REPO: ((registry_image_resource_gcr.repo))
  #@ elif resource_name == "docker-image":
CONTEXT: #@ resource_name + "-resource"
UNPACK_ROOTFS: 'true'
  #@ else:
CONTEXT: #@ resource_name + "-resource"
  #@ end
#@ end

#@ def build_task(resource_name, platform):
task: build
privileged: true
image: oci-build-task
attempts: 2
config:
  platform: linux
  inputs:
  - name: #@ resource_name + "-resource"
  - name: base-image
  - name: builder-image
  outputs:
  - name: built-resource-image
    path: image
  params:
    DOCKERFILE: #@ resource_name + "-resource/Dockerfile"
    ADDITIONAL_TARGETS: tests
    IMAGE_ARG_base_image: base-image/oci
    IMAGE_ARG_builder_image: builder-image/oci
    IMAGE_PLATFORM: #@ platform
    OUTPUT_OCI: true
    _: #@ template.replace(build_params(resource_name))
  run: {path: build}
#@ end

#@ def build_image():
name: build
serial_groups: [build]
plan:
- in_parallel:
  - get: daily-trigger
    trigger: true
  - get: #@ resource_name + "-resource"
    resource: resource-repo
    trigger: true
  - get: base-image
    trigger: true
    params:
      format: oci-layout
  - get: builder-image
    resource: golang-builder
    trigger: true
    params:
      format: oci-layout
  - get: oci-build-task
  - #@ template.replace(extra_get_steps())
- #@ build_task(resource_name, "linux/amd64,linux/arm64")
- #@ template.replace(extra_steps())
- put: resource-image-dev
  no_get: true
  inputs: detect
  params: {image: built-resource-image/image}
#@ end

#@ def scan_image():
name: scan-image
plan:
- in_parallel:
  - get: ci
  - get: resource-repo
    passed:
    - build
  - get: resource-image-dev
    passed: [build]
    params:
      format: oci-layout
    trigger: true
  - get: wolfi-base
    trigger: true
- task: scan
  image: wolfi-base
  file: ci/tasks/trivy-scan/task.yml
  input_mapping: {image: resource-image-dev}
  params:
    IMAGE_PATH: image/oci
#@ end

#@ def extra_steps():
  #@ if resource_name == "docker-image":
- task: smoke-test
  image: built-resource-image
  file: docker-image-resource/ci/smoke-test.yml
  privileged: true
  params:
    REPOSITORY: busybox
  output_mapping:
    fetched-image: busybox
- task: use-fetched-image
  image: busybox
  config:
    platform: linux
    run:
      path: /bin/true
  #@ else: return []
#@ end

#@ def validate_pr():
name: prs
public: true
serial: true
serial_groups:
- validate
plan:
- in_parallel:
  - get: resource-pr
    trigger: true
    version: every
  - get: base-image
    trigger: true
    params:
      format: oci-layout
  - get: builder-image
    resource: golang-builder
    trigger: true
    params:
      format: oci-layout
  - get: oci-build-task
  - #@ template.replace(extra_get_steps())
- put: #@ resource_name + "-resource"
  resource: resource-pr
  inputs: detect
  params:
    context: status
    path: resource-pr
    status: pending
- do:
  - #@ build_task(resource_name, "linux/amd64")
  - #@ template.replace(extra_steps())
  on_failure:
    put: resource-pr
    no_get: true
    inputs: detect
    params:
      context: status
      path: resource-pr
      status: failure
  on_success:
    put: resource-pr
    no_get: true
    inputs: detect
    params:
      context: status
      path: resource-pr
      status: success
#@ end


#@ def extra_get_steps():
  #@ if resource_name == "cf":
- get: cf-cli
  trigger: true
  params: {globs: ["cf-cli*linux*"]}
  #@ else: return []
#@ end

#@ def publish_job(bump):
name: #@ "publish-" + bump
plan:
- in_parallel:
  - get: resource-repo
    passed: [scan-image]
  - get: ci
  - get: resource-image-dev
    passed: [scan-image]
    params: {format: oci}
  - get: resource-image-dev-rootfs
    resource: resource-image-dev
    passed: [scan-image]
    params: {format: rootfs}
  - get: version
    params:
      bump: #@ bump
- task: create-release
  config:
    platform: linux
    image_resource:
      type: registry-image
      source:
        repository: cgr.dev/chainguard/bash
        tag: latest
    inputs:
    - name: version
    - name: resource-image-dev-rootfs
    outputs:
    - name: release
    run:
      path: /bin/bash
      args:
      - "-exc"
      #@yaml/text-templated-strings
      - |
        cat <<EOF > resource_metadata.json
        {
          "type": "(@= resource_name @)",
          "version": "$(cat version/number)",
          "privileged": (@= str(privileged()).lower() @),
          "unique_version_history": (@= str(unique_version_history()).lower() @)
        }
        EOF

        version="$(cat version/number)"
        echo "v${version}" > release/name

        pushd resource-image-dev-rootfs
          cp ../resource_metadata.json .
          tar -czf rootfs.tgz -C rootfs .
          tar -czf ../release/(@= resource_name @)-resource-${version}.tgz rootfs.tgz resource_metadata.json
        popd

- load_var: version
  file: version/version
- in_parallel:
  - put: resource-image
    no_get: true
    inputs: detect
    params:
      image: resource-image-dev/image.tar
      version: ((.:version))
      bump_aliases: true
  - put: resource-repo-release
    no_get: true
    inputs: detect
    params:
      commitish: resource-repo/.git/ref
      generate_release_notes: true
      globs:
      - release/*.tgz
      name: release/name
      tag: version/version
      tag_prefix: v
- put: version
  no_get: true
  inputs: detect
  params:
    file: version/version
#@ end

#@ def rebuild_images():
name: republish-images
serial_groups: [build]
plan:
- in_parallel:
  - get: daily-trigger
    trigger: true
  - get: #@ resource_name + "-resource"
    resource: resource-repo-tags
  - get: base-image
    trigger: true
    params:
      format: oci-layout
  - get: builder-image
    resource: golang-builder
    trigger: true
    params:
      format: oci-layout
  - get: oci-build-task
  - get: version
  - get: ci
  - #@ template.replace(extra_get_steps())
- load_var: version
  file: version/version
- #@ build_task(resource_name, "linux/amd64,linux/arm64")
- #@ template.replace(extra_steps())
- task: date-tag
  file: ci/tasks/tag-version-with-date.yml
  params:
    VERSION: ((.:version))
- put: resource-image
  no_get: true
  inputs: detect
  params:
    image: built-resource-image/image
    version: ((.:version))
    bump_aliases: true
    additional_tags: date-tag/tag
#@ end

#@ def unique_version_history():
#@ return resource_name == "time"
#@ end

#@ def privileged():
#@ return resource_name == "docker-image"
#@ end

---
groups:
- name: main
  jobs:
  - prs
  - build
  - scan-*
  - publish-*
- name: republish
  jobs:
  - republish-*

jobs:
- #@ build_image()
- #@ scan_image()
- #@ validate_pr()
- #@ publish_job("major")
- #@ publish_job("minor")
- #@ publish_job("patch")
- #@ rebuild_images()

resource_types:
- name: pull-request
  type: registry-image
  check_every: 2m
  source:
    repository: teliaoss/github-pr-resource

- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: base-image
  type: registry-image
  icon: docker
  check_every: 6h
  source:
    repository: ((base-image))
    tag: latest

- name: golang-builder
  type: registry-image
  icon: docker
  source:
    repository: concourse/golang-builder
    tag: latest
    username: ((docker.username))
    password: ((docker.password))

- name: wolfi-base
  type: registry-image
  icon: docker
  check_every: 6h
  source:
    repository: cgr.dev/chainguard/wolfi-base

- name: resource-repo
  type: git
  icon: github
  source:
    branch: master
    private_key: ((concourse_bot_private_key))
    uri: #@ "git@github.com:concourse/" + resource_name + "-resource"

- name: resource-repo-tags
  type: git
  icon: github
  source:
    branch: master
    private_key: ((concourse_bot_private_key))
    uri: #@ "git@github.com:concourse/" + resource_name + "-resource"
    tag_filter: "v*"

- name: resource-repo-release
  type: github-release
  icon: package-variant-closed
  source:
    access_token: ((concourse_bot_access_token))
    owner: #@ github_owner()
    repository: #@ resource_name + "-resource"

- name: version
  type: semver
  icon: tag
  source:
    branch: version
    driver: git
    file: version
    private_key: ((concourse_bot_private_key))
    uri: #@ "git@github.com:" + github_owner() + "/" + resource_name + "-resource"

- name: resource-pr
  type: pull-request
  icon: source-pull
  check_every: 2m
  source:
    access_token: ((pull_requests_access_token))
    base_branch: master
    repository: #@ github_owner() + "/" + resource_name + "-resource"

- name: resource-image
  type: registry-image
  icon: docker
  source:
    repository: #@ "concourse/" + resource_name + "-resource"
    username: ((docker.username))
    password: ((docker.password))

- name: resource-image-dev
  type: registry-image
  icon: docker
  source:
    repository: #@ "concourse/" + resource_name + "-resource"
    tag: dev
    password: ((docker.password))
    username: ((docker.username))

- name: ci
  type: git
  icon: github
  source:
    uri: https://github.com/concourse/ci.git
    branch: master

- name: oci-build-task
  type: registry-image
  icon: docker
  source:
    repository: concourse/oci-build-task

- name: daily-trigger
  type: time
  source:
    start: 1AM
    stop: 2AM

#@ if resource_name == "cf":
- name: cf-cli
  type: s3
  source:
    bucket: cf-cli-releases
    regexp: "releases/v([\\d\\.]+)/cf-cli_.*_linux_x86-64.tgz"
    region_name: us-west-1
#@ end
