# Builds a wolfi-base image that contains bash. We wanted a simple base image
# that contains bash and a package manager
resources:
  - name: ci
    type: git
    icon: github
    source:
      uri: https://github.com/concourse/ci.git
      branch: master

  - name: wolfi
    type: registry-image
    icon: docker
    source:
      repository: chainguard/wolfi-base
      tag: latest
      username: ((docker.username))
      password: ((docker.password))

  - name: bash
    type: registry-image
    icon: docker
    source:
      repository: concourse/bash
      tag: latest
      username: ((docker.username))
      password: ((docker.password))

  - name: oci-build-task
    type: registry-image
    icon: docker
    source:
      repository: concourse/oci-build-task

jobs:
  - name: build
    plan:
      - in_parallel:
          - get: wolfi
            trigger: true
            params:
              format: oci-layout
          - get: ci
          - get: oci-build-task
      - task: build
        image: oci-build-task
        privileged: true
        config:
          platform: linux
          inputs:
            - name: ci
            - name: wolfi
          outputs:
            - name: image
          params:
            CONTEXT: ci/dockerfiles/bash
            IMAGE_PLATFORM: linux/arm64,linux/amd64
            IMAGE_ARG_base_image: wolfi/oci
          run:
            path: build
      - put: bash
        no_get: true
        params:
          image: image/image
