resource_types:
- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: chart-repo-store
  type: gcs-resource
  source:
    bucket: concourse-chart
    json_key: ((concourse_chart_bucket_json_key))
    regexp: ".*"
- name: concourse-chart
  type: git
  source:
    uri: https://github.com/concourse/concourse-chart
    branch: chart-name
jobs:
- name: build-chart
  public: true
  plan:
  - get: concourse-chart
  - task: build
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: cirocosta/charts-maintenance
      run:
        path: sh
        args:
        - -ceu
        - |
          helm init --client-only
          helm repo remove local
          helm repo update
          helm package -u -d $DESTINATION_DIR $CHART_DIR
          helm repo index $DESTINATION_DIR

      inputs:
      - name: concourse-chart
      outputs:
      - name: repository
    params:
      CHART_DIR: ./concourse-chart
      DESTINATION_DIR: ./repository
  - put: chart-repo-store
    params:
      file: repository/index.yaml
  - put: chart-repo-store
    params:
      file: repository/*.tgz
