---
resource_types:
  - name: github
    type: registry-image
    source:
      repository: pixelairio/github-resource
      tag: latest

  - name: helm-chart
    type: registry-image
    source: { repository: linkyard/helm-chart-resource, tag: 2.17.0 }

resources:
  - name: chart-pr
    type: github
    icon: source-pull
    source:
      kind: commits-from-prs
      repository: concourse/concourse-chart
      target_branch: ((branch))
      access_token: ((pr_access_token))

  - name: concourse
    type: git
    icon: github
    source:
      uri: https://github.com/concourse/concourse.git
      branch: ((concourse_base_branch))

  - name: ci
    type: git
    icon: github
    source:
      uri: https://github.com/concourse/ci.git
      branch: master

  - name: concourse-image
    type: registry-image
    icon: docker
    source:
      repository: ((concourse_image_name))
      tag: ((concourse_image_tag))
      username: ((docker.username))
      password: ((docker.password))

  - name: unit-image
    type: registry-image
    icon: docker
    source:
      repository: concourse/unit
      username: ((docker.username))
      password: ((docker.password))

  - name: prometheus-chart
    type: helm-chart
    icon: ship-wheel
    source:
      chart: prometheus-community/prometheus
      repos:
        - name: prometheus-community
          url: https://prometheus-community.github.io/helm-charts

  - name: postgresql-chart-git
    type: git
    check_every: 24h
    source:
      uri: "https://github.com/bitnami/charts.git"
      tag_filter: postgresql/((postgresql_major))*

jobs:
  - name: k8s-topgun
    serial: true
    public: true
    on_failure: &failure-status-update
      put: pr-status-update
      resource: chart-pr
      no_get: true
      params:
        name: concourse-ci/$BUILD_JOB_NAME
        ref: ((.:chart-pr.ref))
        status: failure
    on_success: &success-status-update
      put: pr-status-update
      resource: chart-pr
      no_get: true
      params:
        name: concourse-ci/$BUILD_JOB_NAME
        ref: ((.:chart-pr.ref))
        status: success
    plan:
      - in_parallel:
          - do:
            - get: chart-pr
              tags: [k8s-topgun]
            - &pending-status-update
              put: pr-status-update
              resource: chart-pr
              params:
                name: concourse-ci/$BUILD_JOB_NAME
                ref: ((.:chart-pr.ref))
                status: pending
          - get: concourse
            tags: [k8s-topgun]
          - get: concourse-image
            tags: [k8s-topgun]
          - get: ci
            tags: [k8s-topgun]
          - get: unit-image
            tags: [k8s-topgun]
          - get: prometheus-chart
            tags: [k8s-topgun]
            params: { untar: true }
          - get: postgresql-chart-git
            tags: [k8s-topgun]
      - task: k8s-topgun
        tags: [k8s-topgun]
        file: ci/tasks/k8s-topgun/task.yml
        input_mapping:
          concourse-chart: chart-pr
          concourse-rc-image: concourse-image
        image: unit-image
        params:
          IN_CLUSTER: "true"
          SERVICE_ACCOUNT_KEY: ((k8s_topgun.service_account_key))
          CONCOURSE_IMAGE_NAME: ((concourse_image_name))

  - name: lint-and-install-test
    public: true
    on_failure: *failure-status-update
    on_success: *success-status-update
    plan:
      - in_parallel:
          - do:
            - get: chart-pr
              trigger: true
              version: every
              tags: [k8s-topgun]
            - *pending-status-update
          - get: ci
            tags: [k8s-topgun]
          - get: unit-image
            tags: [k8s-topgun]
      - task: lint-and-install-test
        tags: [k8s-topgun]
        file: ci/tasks/k8s-lint-and-install/task.yml
        image: unit-image
        input_mapping: { concourse: chart-pr }
        params:
          SERVICE_ACCOUNT_KEY: ((k8s_topgun.service_account_key))

  - name: unit-tests
    public: true
    on_failure: *failure-status-update
    on_success: *success-status-update
    plan:
      - in_parallel:
          - do:
            - get: chart-pr
              trigger: true
              version: every
              tags: [k8s-topgun]
            - *pending-status-update
          - get: ci
            tags: [k8s-topgun]
          - get: unit-image
            tags: [k8s-topgun]
      - task: unit-tests
        tags: [k8s-topgun]
        file: ci/tasks/helm-chart-unit-tests/task.yml
        image: unit-image
        input_mapping: { chart: chart-pr }
