resource_types:
- name: slack-notifier
  type: registry-image
  source: {repository: mockersf/concourse-slack-notifier}

resources:
- name: every-week
  type: time
  source:
    interval: 24h
    days: [Monday]

- name: every-day
  type: time
  source:
    interval: 24h

- name: dockerfile
  type: git
  icon: github
  source:
    uri: https://github.com/concourse/ci.git
    branch: master
    paths:
      - dockerfiles/infrastructure-report

- name: ci
  type: git
  icon: github
  source:
    uri: https://github.com/concourse/ci.git
    branch: master

- name: image
  type: registry-image
  icon: docker
  source:
    repository: gcr.io/cf-concourse-production/infrastructure-report
    tag: latest
    username: _json_key
    password: ((gcr_gcp_key_json))

- name: oci-build-task
  type: registry-image
  icon: docker
  source:
    repository: vito/oci-build-task

- name: ubuntu-image
  type: registry-image
  icon: docker
  source:
    repository: ubuntu
    tag: noble
    username: ((docker.username))
    password: ((docker.password))

- name: notify
  type: slack-notifier
  icon: slack
  source:
    url: ((slack_hooks.concourse-interrupt))
    username: ((basic_auth.username))
    password: ((basic_auth.password))
    concourse_url: https://ci.concourse-ci.org

jobs:
- name: build-image
  plan:
  - get: ci
    resource: dockerfile
    trigger: true
  - in_parallel:
    - get: oci-build-task
    - get: ubuntu-image
      params: {format: oci}
  - task: build
    image: oci-build-task
    privileged: true
    config:
      platform: linux
      params:
        CONTEXT: ci/dockerfiles/infrastructure-report
        IMAGE_ARG_base_image: ubuntu-image/image.tar
      inputs:
        - name: ci
        - name: ubuntu-image
      outputs:
        - name: image
      caches:
        - path: cache
      run: {path: build}
  - put: image
    params: {image: image/image.tar}

- name: clean-up-bosh-director
  plan:
  - get: every-day
    trigger: true
  - get: image
  - task: clean
    image: image
    config:
      platform: linux
      params:
        GCP_JSON_KEY: ((gcp_json_key))
      run:
        path: bash
        args:
        - "-ec"
        - |
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp.key.json
          cat > $GOOGLE_APPLICATION_CREDENTIALS <<EOF
          $GCP_JSON_KEY
          EOF

          project=$(echo $GCP_JSON_KEY | jq -r '.project_id')
          gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS --project $project

          gsutil -m cp -r gs://bosh-topgun-bbl-state/ . > /dev/null 2>&1
          pushd bosh-topgun-bbl-state > /dev/null
            eval "$(bbl print-env)"

            # clean up bosh director for disk space releasing
            bosh clean-up -n
          popd > /dev/null
  on_success:
    put: notify
    params:
      mode: concise
      message: Bosh cleaned up
      alert_type: success

- name: generate-report
  plan:
  - get: every-week
    trigger: true
  - in_parallel:
    - get: ci
    - get: image
  - task: report
    image: image
    file: ci/tasks/infrastructure-report.yml
    params:
      GCP_JSON_KEY: ((gcp_json_key))
  on_success:
    put: notify
    params:
      mode: concise
      message: Infrastructure report generated, open build logs to view
      alert_type: success
