---
jobs:
- name: promote-concourse
  serial: true
  plan:
  - get: concourse
    trigger: true
  - put: concourse-master
    params:
      repository: concourse
      merge: true

- name: promote-cbd
  serial: true
  plan:
  - get: cbd
    trigger: true
  - put: cbd-master
    params:
      repository: cbd
      merge: true

- name: publish-docs
  public: true
  serial: true
  plan:
  - in_parallel:
    - get: concourse
      trigger: true
    - get: docs
  - task: build-docs
    file: docs/ci/build.yml
    params:
      ANALYTICS_ID: ((analytics_id))
      GITHUB_TOKEN: ((concourse_github_dummy.access_token))
  - put: docs-gh-pages
    params: {repository: built-docs}


resources:
- name: cbd
  type: git
  icon: &git-icon github
  source:
    uri: https://github.com/concourse/concourse-bosh-deployment
    tag_filter: v((release_version))

- name: cbd-master
  type: git
  icon: *git-icon
  source:
    uri: git@github.com:concourse/concourse-bosh-deployment.git
    branch: master
    private_key: ((concourse_deployment_repo_private_key))

- name: concourse
  type: git
  icon: *git-icon
  source:
    uri: https://github.com/concourse/concourse
    tag_filter: v((release_version))

- name: concourse-master
  type: git
  icon: *git-icon
  source:
    uri: git@github.com:concourse/concourse.git
    branch: master
    private_key: ((concourse_repo_private_key))

- name: docs
  type: git
  icon: *git-icon
  source:
    uri: https://github.com/concourse/docs
    branch: master

- name: docs-gh-pages
  type: git
  icon: *git-icon
  source:
    uri: git@github.com:concourse/docs
    branch: gh-pages
    private_key: ((docs_deploy_key))
