---
resource_types:
- name: bosh-deployment
  type: registry-image
  source: {repository: cloudfoundry/bosh-deployment-resource}

- name: pull-request
  type: registry-image
  source: {repository: teliaoss/github-pr-resource}

resources:
- name: concourse-master
  type: git
  icon: github-circle
  source:
    uri: https://github.com/concourse/concourse

- name: concourse-pr
  type: pull-request
  icon: source-pull
  source:
    repository: concourse/concourse
    access_token: ((pull_requests_access_token))

- name: baggageclaim-master
  type: git
  icon: github-circle
  source:
    uri: https://github.com/concourse/baggageclaim

- name: baggageclaim-pr
  type: pull-request
  icon: source-pull
  source:
    repository: concourse/baggageclaim
    access_token: ((pull_requests_access_token))

- name: docs-master
  type: git
  icon: github-circle
  source:
    uri: https://github.com/concourse/docs

- name: docs-pr
  type: pull-request
  icon: source-pull
  source:
    repository: concourse/docs
    access_token: ((pull_requests_access_token))

- name: ci
  type: git
  icon: github-circle
  source:
    uri: https://github.com/concourse/ci

- name: dev-image
  type: registry-image
  icon: docker
  source: {repository: concourse/dev}

- name: unit-image
  type: registry-image
  icon: docker
  source: {repository: concourse/unit}

- name: baggageclaim-ci
  type: registry-image
  icon: docker
  source: {repository: concourse/baggageclaim-ci}

- name: postgres-image
  type: registry-image
  icon: docker
  source: {repository: postgres}

jobs:
- name: unit
  public: true
  max_in_flight: 3
  on_failure:
    put: concourse-pr
    inputs: [concourse-pr]
    params: {path: concourse-pr, status: failure, context: unit}
    tags: [pr]
    get_params: {skip_download: true}
  on_success:
    put: concourse-pr
    inputs: [concourse-pr]
    params: {path: concourse-pr, status: success, context: unit}
    tags: [pr]
    get_params: {skip_download: true}
  plan:
  - in_parallel:
    - get: concourse-pr
      trigger: true
      version: every
      tags: [pr]
    - get: concourse-master
      tags: [pr]
    - get: unit-image
      tags: [pr]
    - get: ci
      tags: [pr]
  - put: concourse-pr
    inputs: [concourse-pr]
    params: {path: concourse-pr, status: pending, context: unit}
    tags: [pr]
    get_params: {list_changed_files: true, skip_download: true}
  - task: check-migration-order
    timeout: 5m
    file: ci/tasks/check-migration-order.yml
    tags: [pr]
  - task: yarn-analyse
    attempts: 3
    file: ci/tasks/yarn-analyse.yml
    input_mapping: {concourse: concourse-pr}
    tags: [pr]
  - task: yarn-test
    attempts: 3
    file: ci/tasks/yarn-test.yml
    input_mapping: {concourse: concourse-pr}
    tags: [pr]
  - task: yarn-benchmark
    attempts: 3
    file: ci/tasks/yarn-benchmark.yml
    input_mapping: {concourse: concourse-pr}
    tags: [pr]
  - task: unit
    image: unit-image
    attempts: 3
    timeout: 1h
    file: ci/tasks/unit.yml
    input_mapping: {concourse: built-concourse}
    tags: [pr]

- name: testflight
  public: true
  max_in_flight: 3
  on_failure:
    put: concourse-pr
    inputs: [concourse-pr]
    params: {path: concourse-pr, status: failure, context: testflight}
    tags: [pr]
    get_params: {skip_download: true}
  on_success:
    put: concourse-pr
    inputs: [concourse-pr]
    params: {path: concourse-pr, status: success, context: testflight}
    tags: [pr]
    get_params: {skip_download: true}
  plan:
  - in_parallel:
    - get: concourse-pr
      trigger: true
      version: every
      tags: [pr]
    - get: dev-image
      params: {format: oci}
      tags: [pr]
    - get: postgres-image
      params: {format: oci}
      tags: [pr]
    - get: ci
  - put: concourse-pr
    inputs: [concourse-pr]
    params: {path: concourse-pr, status: pending, context: testflight}
    tags: [pr]
    get_params: {list_changed_files: true, skip_download: true}
  - task: yarn-build
    attempts: 3
    file: ci/tasks/yarn-build.yml
    input_mapping: {concourse: concourse-pr}
    tags: [pr]
  - task: testflight
    timeout: 1h
    privileged: true
    file: ci/tasks/docker-compose-testflight.yml
    input_mapping: {concourse: built-concourse}
    params: {BUILD: true}
    tags: [pr]

- name: watsjs
  public: true
  max_in_flight: 3
  on_failure:
    put: concourse-pr
    inputs: [concourse-pr]
    params: {path: concourse-pr, status: failure, context: watsjs}
    tags: [pr]
    get_params: {skip_download: true}
  on_success:
    put: concourse-pr
    inputs: [concourse-pr]
    params: {path: concourse-pr, status: success, context: watsjs}
    tags: [pr]
    get_params: {skip_download: true}
  plan:
  - in_parallel:
    - get: concourse-pr
      trigger: true
      version: every
      tags: [pr]
    - get: dev-image
      params: {format: oci}
      tags: [pr]
    - get: postgres-image
      params: {format: oci}
      tags: [pr]
    - get: ci
  - put: concourse-pr
    inputs: [concourse-pr]
    params: {path: concourse-pr, status: pending, context: watsjs}
    tags: [pr]
    get_params: {list_changed_files: true, skip_download: true}
  - task: yarn-build
    attempts: 3
    file: ci/tasks/yarn-build.yml
    input_mapping: {concourse: concourse-pr}
    tags: [pr]
  - task: watsjs
    timeout: 1h
    privileged: true
    file: ci/tasks/docker-compose-watsjs.yml
    input_mapping: {concourse: built-concourse}
    params: {BUILD: true}
    tags: [pr]

- name: baggageclaim
  public: true
  on_failure:
    put: baggageclaim-pr
    params: {path: baggageclaim-pr, status: failure, context: unit}
    tags: [pr]
  on_success:
    put: baggageclaim-pr
    params: {path: baggageclaim-pr, status: success, context: unit}
    tags: [pr]
  plan:
  - in_parallel:
    - get: baggageclaim-pr
      trigger: true
      version: every
      tags: [pr]
    - get: baggageclaim-master
      tags: [pr]
    - get: baggageclaim-ci
    - get: ci
  - put: baggageclaim-pr
    params: {path: baggageclaim-pr, status: pending, context: unit}
    tags: [pr]
  - task: unit-linux
    image: baggageclaim-ci
    privileged: true
    timeout: 1h
    file: baggageclaim-master/ci/unit-linux.yml
    input_mapping: {baggageclaim: baggageclaim-pr}
    tags: [pr]

- name: docs
  public: true
  on_failure:
    put: docs-pr
    inputs: [docs-pr]
    params: {path: docs-pr, status: failure, context: build}
    tags: [pr]
  on_success:
    put: docs-pr
    inputs: [docs-pr]
    params: {path: docs-pr, status: success, context: build}
    tags: [pr]
  plan:
  - in_parallel:
    - get: docs-pr
      trigger: true
      version: every
      tags: [pr]
    - get: docs-master
      tags: [pr]
  - put: docs-pr
    params: {path: docs-pr, status: pending, context: build}
    tags: [pr]
  - task: build
    file: docs-master/ci/build.yml
    input_mapping: {docs: docs-pr}
    params:
      GITHUB_TOKEN: ((concourse_github_dummy.access_token))
    tags: [pr]
