---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/unit

inputs:
- name: ci
- name: concourse-release-repo
- name: linux-rc
- name: windows-rc

outputs:
- name: bumped-concourse-release-repo

params:
  access_key_id: ""
  secret_access_key: ""

run:
  path: ci/tasks/bump-concourse-blobs/run.sh
