platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/oci-build-task}

params:
  IMAGE_ARG_base_image: busybox/image.tar
  DOCKERFILE: ci/dockerfiles/resource-types/Dockerfile
  REPOSITORY: concourse/dev

inputs:
- name: ci
- name: bosh-io-release-resource
- name: bosh-io-stemcell-resource
- name: docker-image-resource
- name: git-resource
- name: github-release-resource
- name: hg-resource
- name: mock-resource
- name: pool-resource
- name: registry-image-resource
- name: s3-resource
- name: semver-resource
- name: time-resource
- name: tracker-resource
- name: busybox

outputs:
- name: image

run:
  path: ci/tasks/build-resource-types-image/config.yml
