---
platform: linux

image_resource:
  type: registry-image
  source: { repository: concourse/unit }

inputs:
  - name: concourse
  - name: ci

caches:
  - path: gopath

run:
  path: ci/tasks/unit/run.sh
