---
platform: linux

image_resource:
  type: registry-image
  source: { repository: concourse/unit }

inputs:
  - name: concourse
  - name: ci
  - name: endpoint-info

caches:
  - path: gopath
  - path: concourse/web/wats/node_modules

run:
  path: ci/tasks/smoke-test/run.sh
