---
platform: linux

image_resource:
  type: registry-image
  source: { repository: concourse/unit }

inputs:
  - name: concourse
  - name: ci

caches:
  - path: concourse/node_modules
  - path: concourse/web/elm/elm-stuff

run:
  path: ci/tasks/yarn-analyse/run.sh
