---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

params:
  bucket_name: ""
  access_key_id: ""
    secret_access_key: ""
    custom_endpoint: ""

inputs:
- name: concourse-release
- name: postgres-release
- name: bpm-release
- name: ci

run:
  path: ci/tasks/bosh-upload-releases/run.sh
