#!/bin/bash

if [ -d version ]; then
  version=v$(cat version/version)
elif [ "$#" -eq 1 ]; then
  version=$1
else
  echo "version must be specified, either as an argument or an input" >&2
  exit 1
fi

echo "$version" > ./built-notes/release-name
# if this fails, it's because we forgot to manually promote latest.md to $version.md
cp release-notes/release-notes/"$version".md ./built-notes/notes.md
