#!/bin/bash

LAST_COMMIT_SHA=$(cat repo/.git/ref)
RELEASE_VERSION=$(cat version/version)

FILE=built-notes/notes.md

chmod +x release-me/releaseme
./release-me/releaseme generate \
  --github-token=$GITHUB_TOKEN \
  --github-owner=$GITHUB_OWNER \
  --github-repo=$GITHUB_REPO \
  --github-branch=$GITHUB_BRANCH \
  --last-commit-SHA=$LAST_COMMIT_SHA \
  --release-version=$RELEASE_VERSION \
  --ignore-authors=dependabot \
  > $FILE

if [ -f resource-type-versions/versions.yml ]; then
  cat >> $FILE <<EOF

## 📦 Bundled resource types

<details>

EOF
  cat resource-type-versions/versions.yml | while read line; do
    name=$(printf $line | cut -d':' -f1 | xargs)
    version=$(printf $line | cut -d':' -f2 | xargs)
    ghlink="https://github.com/concourse/$name-resource/releases/tag/$version"
    echo "- $name: [$version]($ghlink)" >> $FILE
  done
fi
