#!/bin/bash

set -e -u

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

source ci/tasks/scripts/cgroup-helpers.sh

main() {
  sanitize_cgroups
  run_test
}

run_test() {
  cd concourse

  go mod download
  go install github.com/onsi/ginkgo/ginkgo

  ginkgo -r -nodes=4 -race -keepGoing -slowSpecThreshold=15 ./worker/backend/integration "$@"
}

main "$@"
