#!/bin/bash

set -e -u

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

source ci/tasks/scripts/cgroup-helpers.sh

main() {
  sanitize_cgroups
  run_test
}

run_test() {
  cd concourse

  go mod download
  go test -v -race ./worker/runtime/integration
}

main
