#!/bin/bash

set -e -u

export PIPELINE_NAME=test-pipeline

export inputs=$PWD

source ci/tasks/scripts/docker-helpers.sh

start_docker

[ -d dev-image ] && docker load -i dev-image/image.tar
[ -d concourse-image ] && docker load -i concourse-image/image.tar
[ -d postgres-image ] && docker load -i postgres-image/image.tar

[ -f dev-image/tag ] && export CONCOURSE_DEV_REF=":$(cat dev-image/tag)"
if [ -f concourse-image/tag ]; then
  export CONCOURSE_LATEST_TAG=$(cat concourse-image/tag)
else
  export CONCOURSE_LATEST_TAG=latest
fi

cd concourse

# generate keys for the cluster
export CONCOURSE_KEYS=$PWD/keys
$inputs/ci/tasks/scripts/generate-keys

DOCKER_COMPOSE_FLAGS="-f docker-compose.yml -f $inputs/ci/overrides/docker-compose.ci-guardian.yml -f $inputs/ci/overrides/docker-compose.ci-fast-events.yml"

# start with rc and set up
echo "Deploying Concourse RC"
if [ "$BUILD" = "true" ]; then
  docker-compose \
    $DOCKER_COMPOSE_FLAGS \
    up --build -d
else
  docker-compose \
    $DOCKER_COMPOSE_FLAGS \
    -f $inputs/ci/overrides/docker-compose.no-build.yml \
    up --no-build -d
fi

trap stop_docker_compose EXIT SIGTERM SIGINT
function stop_docker_compose() {
  docker-compose -f $inputs/concourse/docker-compose.yml logs > docker-compose.log
  docker-compose -f $inputs/concourse/docker-compose.yml down
  stop_docker
}

$inputs/ci/tasks/scripts/create-upgrade-downgrade-pipeline

# perform down migrations
downgrade_to=$(docker run concourse/concourse:latest migrate --supported-db-version)
echo "Migrating Concourse DB to $downgrade_to"
docker-compose exec web concourse migrate --migrate-db-to-version $downgrade_to

# this is needed so that the worker unregisters with the ATC.
# docker-compose seems to recreate the web before recreating the worker,
# and the worker is unable to unregister with the ATC since the ATC may
# not be ready to receive requests.
docker-compose stop worker

# downgrade and verify
echo "Deploying Concourse released version"
docker-compose \
  $DOCKER_COMPOSE_FLAGS \
  -f $inputs/ci/overrides/docker-compose.no-build.yml \
  -f $inputs/ci/overrides/docker-compose.latest.yml \
  up --no-build -d

# This is done temporarily to bypass fly issue https://github.com/concourse/concourse/issues/5938
$inputs/ci/tasks/scripts/verify-upgrade-downgraded-pipeline-temporary

# this is needed so that the worker unregisters with the ATC.
# docker-compose seems to recreate the web before recreating the worker,
# and the worker is unable to unregister with the ATC since the ATC may
# not be ready to receive requests.
docker-compose stop worker

# upgrade back and verify
if [ "$BUILD" = "true" ]; then
  docker-compose \
    $DOCKER_COMPOSE_FLAGS \
    up --no-build -d
else
  docker-compose \
    $DOCKER_COMPOSE_FLAGS \
    -f $inputs/ci/overrides/docker-compose.no-build.yml \
    up --no-build -d
fi

$inputs/ci/tasks/scripts/verify-upgrade-downgrade-pipeline

# run smoke tests
cd web/wats
stty columns 80 # for better yarn output
yarn install
yarn test -v --color test/smoke.js
