#!/bin/bash
# vim: set ft=sh

set -e -u

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

cd concourse/fly

go mod download

go install github.com/onsi/ginkgo/ginkgo

# CGO is required for go test -race
CGO_ENABLED=1 ginkgo -r -p -race "$@"
