#!/bin/bash
# vim: set ft=sh

set -e -x

export GOPATH=$PWD/gopath
export PATH=$PWD/gopath/bin:$PATH

platform="$(go env GOOS)"
arch="$(go env GOARCH)"

output="$PWD/fly-${platform}"

ldflags=""
if [ -e final-version/version ]; then
  final_version="$(cat final-version/version)"
  ldflags="-X github.com/concourse/concourse.Version=${final_version}"
fi

tags=""
platform_flags=""

pushd concourse
  ldflags+=' -extldflags "-static"'

  if [[ "$platform" == "darwin" ]]; then
    export CGO_ENABLED=1
    tags+=' osusergo'
    platform_flags+='-buildvcs=false'
  fi

  go build -a -tags "$tags" -ldflags "$ldflags" $platform_flags -o $output/fly ./fly
popd

pushd $output
  archive=fly-$platform-$arch.tgz
  tar -czf $archive fly
  shasum "$archive" > "${archive}.sha1"
popd
