#!/bin/bash
# vim: set ft=sh

set -e -u

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

cd concourse/fly

go mod download

go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo

ginkgo -r -p -race "$@"
