#!/bin/bash
# vim: set ft=sh

set -e -x

export GOPATH=$PWD/gopath
export PATH=$PWD/gopath/bin:$PATH

platform="$(go env GOOS)"
arch="$(go env GOARCH)"

output="$PWD/fly-${platform}"

ldflags=""
if [ -e final-version/version ]; then
  final_version="$(cat final-version/version)"
  ldflags="-X github.com/concourse/concourse.Version=${final_version}"
fi

pushd concourse
  export CGO_ENABLED=1

  if [ "$platform" = "linux" ]; then
    ldflags+=' -extldflags "-static"'
    if [ "$USE_EXTERNAL_LINKER" = "true" ]; then
      ldflags+=' -linkmode external'
    fi
  fi

  go build --tags 'netgo osusergo' -a -ldflags "$ldflags" -o $output/fly ./fly

  if [ "$platform" = "linux" ] && which ldd && ldd $output/fly; then
    echo "binary is not static; aborting"
    exit 1
  fi
popd

pushd $output
  archive=fly-$platform-$arch.tgz
  tar -czf $archive fly
  shasum "$archive" > "${archive}.sha1"
popd
