#!/bin/sh
# vim: set ft=sh

set -e -x

stty cols 80
src="$PWD/src"
message_file="$PWD/message/message"
apk add git

cd ci/tasks/scripts
yarn install
yarn blame $(git -C "$src" rev-parse HEAD) "$message_file"
