#!/bin/sh

set -e

syft packages docker-archive:image-ubuntu/image.tar -o cyclonedx-json > concourse-ubuntu.sbom

tar -xvf tas-cve/tas-cve-*.tgz linux_x86-64/tas-cve -C /usr/bin

chmod +x /usr/bin/tas-cve

tas-cve uploadBom --bom concourse-ubuntu.sbom --name concourse-dev-image --version dev
