#!/bin/bash
# vim: set ft=sh

set -e -u

readonly SKIP="${SKIP:-}"
readonly DIR=$(cd $(dirname $0) && pwd)

source "$DIR/k8s-helpers.sh"

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

gke_auth

mkdir -p helm-charts/stable
cp -r prometheus-chart/prometheus helm-charts/stable
cp -r postgresql-chart-git/bitnami/postgresql helm-charts/stable
ls -l helm-charts/stable/postgresql

export CONCOURSE_IMAGE_DIGEST="$(cat concourse-rc-image/digest)"
export CONCOURSE_IMAGE_TAG="$(cat concourse-rc-image/tag)"
export HELM_CHARTS_DIR="$(realpath ./helm-charts)"
export CONCOURSE_CHART_DIR="$(realpath ./concourse-chart)"

cd concourse

go mod download

go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo

ginkgo -nodes=8 -race -keep-going -poll-progress-after=900s -flake-attempts=3 -skip="$SKIP" ./topgun/k8s/ "$@"
