#!/bin/bash

# k8s-deploy - deploys Concourse on a K8S cluster using
# a helm charts provided under `./charts`.
#
# ps.: this script is meant to be used for smoke tests.

set -o errexit
set -o nounset
set -o pipefail

# Variables that can be either be configured
# by making use of environment variables when
# executing `k8s-deploy` or the default values.
readonly CONCOURSE_DIGEST="${CONCOURSE_DIGEST:-$(cat ./image-info/digest)}"
readonly CONCOURSE_IMAGE="${CONCOURSE_IMAGE:-concourse/dev}"
readonly RELEASE_NAME="${RELEASE_NAME:-concourse-smoke}"
readonly VALUES=${VALUES:-""}

main() {
  eventually_populate_kube_config
  run_helm_deploy
}

eventually_populate_kube_config() {
  mkdir -p ~/.kube

  if [[ -f ~/.kube/config ]]; then
    return 0
  fi

  if [[ -z $KUBE_CONFIG ]]; then
    echo "Error: KUBE_CONFIG must be specified when ~/.kube/config doesnt exist"
    exit 1
  fi

  echo "$KUBE_CONFIG" >~/.kube/config
}

run_helm_deploy() {
  local chart=./charts/stable/concourse

  if [[ ! -d ./values && -z "$VALUES" ]]; then
    echo "$VALUES" > ./values/values.yaml
  fi

  helm init --upgrade --wait
  helm version
  helm dependency update $chart
  helm upgrade \
    --install \
    --namespace "$RELEASE_NAME" \
    --recreate-pods \
    --set "image=$CONCOURSE_IMAGE"\
    --set "imageDigest=$CONCOURSE_IMAGE_DIGEST"\
    --values ./values/values.yaml \
    --wait \
    $RELEASE_NAME \
    $chart

#   kubectl \
#     --namespace "$RELEASE_NAME" \
#     rollout status deployment \
#     "$RELEASE_NAME-web"
}

main "$@"
