#!/bin/bash
# vim: set ft=sh

set -e -u

readonly SKIP="${SKIP:-}"

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

mkdir -p ~/.kube

if [ ! -f ~/.kube/config ]; then
  echo "$KUBE_CONFIG" > ~/.kube/config
fi

# TODO: tech-debt for maintaining 6.3.x version of the chart which uses Helm v2
# Remove when 6.3.x no longer needs to be supported
if [[ $HELM_VERSION == "2" ]]; then
  rm -f /usr/local/bin/helm
  mv /usr/local/bin/helm2 /usr/local/bin/helm
fi
# END of tech-debt

mkdir -p helm-charts/stable
cp -r prometheus-chart/prometheus helm-charts/stable
cp -r postgresql-chart/postgresql helm-charts/stable

export CONCOURSE_IMAGE_DIGEST="$(cat concourse-rc-image/digest)"
export CONCOURSE_IMAGE_TAG="$(cat concourse-rc-image/tag)"
export HELM_CHARTS_DIR="$(realpath ./helm-charts)"
export CONCOURSE_CHART_DIR="$(realpath ./concourse-chart)"

cd concourse

go mod download

go install github.com/onsi/ginkgo/ginkgo

# CGO is required for go test -race
CGO_ENABLED=1 ginkgo -nodes=8 -race -keepGoing -slowSpecThreshold=900 -flakeAttempts=3 -skip="$SKIP" ./topgun/k8s/ "$@"
