#!/bin/bash

# k8s-deploy - deploys Concourse on a K8S cluster using
# a helm charts provided under `./charts`.
#
# ps.: this script is meant to be used for smoke tests.

set -o errexit
set -o nounset
set -o pipefail

# Variables that can be either be configured
# by making use of environment variables when
# executing `k8s-deploy` or the default values.
readonly RELEASE_NAME="${RELEASE_NAME:-concourse-smoke}"
readonly CONCOURSE_IMAGE="${CONCOURSE_IMAGE:-concourse/dev}"
readonly CONCOURSE_DIGEST="${CONCOURSE_DIGEST:-$(cat ./image-info/digest)}"
readonly DIR=$(cd $(dirname $0) && pwd)

source "$DIR/k8s-helpers.sh"

main() {
  gke_auth
  run_helm_deploy
}

run_helm_deploy() {
  local chart=./concourse-chart

  helm version
  helm dependency update $chart
  helm upgrade \
    --install \
    --recreate-pods \
    --wait \
    --namespace "$RELEASE_NAME" \
    --create-namespace \
    --set "concourse.web.auth.mainTeam.localUser=admin" \
    --set "concourse.web.kubernetes.enabled=false" \
    --set "concourse.worker.baggageclaim.driver=overlay" \
    --set "image=$CONCOURSE_IMAGE" \
    --set "imageDigest=$CONCOURSE_DIGEST" \
    --set "persistence.enabled=false" \
    --set "postgresql.persistence.enabled=false" \
    --set "secrets.localUsers=admin:admin\,guest:guest" \
    --set "web.livenessProbe.failureThreshold=3" \
    --set "web.livenessProbe.initialDelaySeconds=10" \
    --set "web.livenessProbe.periodSeconds=10" \
    --set "web.livenessProbe.timeoutSeconds=3" \
    --set "worker.replicas=1" \
    $RELEASE_NAME \
    $chart

  kubectl \
    --namespace "$RELEASE_NAME" \
    rollout status deployment \
    "$RELEASE_NAME-web"
}

main "$@"
