#!/bin/bash
# vim: set ft=sh

set -e -u

readonly RELEASE_NAME="$RELEASE_NAME"
readonly DIR=$(cd $(dirname $0) && pwd)

source "$DIR/k8s-helpers.sh"

main () {
  gke_auth
  forward_atc_port
  run_test
}

forward_atc_port () {
  ulimit -n 65536
  kubectl port-forward \
    --namespace $RELEASE_NAME \
    deployment/$RELEASE_NAME-web \
    --pod-running-timeout=5m \
    8080:8080 >/dev/null &
}

run_test () {
  ATC_URL="http://127.0.0.1:8080" $DIR/smoke
}

main
