#!/bin/bash
# vim: set ft=sh

set -e -u

for pipeline in $PIPELINES; do
  echo "rendering '$pipeline' pipeline config..."
  ytt -f pipelines/$pipeline  -f deployments.yml \
    > rendered_pipelines/$pipeline
  echo ""
done

