#!/bin/bash

set -e -u

for resource in $RESOURCES; do
  echo "rendering '$resource' pipeline config..."
  ytt --data-value resource_name=$resource -f pipelines/pipelines/resources/ \
    > rendered_pipelines/$resource.yml
  echo ""
done
