#!/bin/sh

set -e

echo "unpacking vulnerability db"
cache_dir=`pwd`
mkdir -p "${cache_dir}/db"
tar -xzf trivy-db/trivy-offline.db.tgz -C "${cache_dir}/db"

echo "scanning base os"
trivy \
  --cache-dir "${cache_dir}" \
  --quiet \
  image \
  --severity "HIGH,CRITICAL" \
  --ignore-unfixed \
  --exit-code 1 \
  --input image/image.tar
