#!/bin/bash

set -e -u

outputs=$PWD/outputs

deployment_path=ci/deployments/smoke

if [ -d linux-rc ]; then
  cp linux-rc/concourse-*.tgz $deployment_path/concourse.tgz
fi

cd $deployment_path

echo "$GCP_KEY" > keys/gcp.json

echo "$SSH_KEY" > keys/id_rsa
chmod 0600 keys/id_rsa
ssh-keygen -y -f keys/id_rsa > keys/id_rsa.pub

curl -fsSL https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip -o /tmp/terraform.zip
unzip -o /tmp/terraform.zip -d /usr/local/bin
rm /tmp/terraform.zip

terraform init

terraform workspace select "$WORKSPACE" || \
  terraform workspace new "$WORKSPACE"

terraform apply --auto-approve --var project=$GCP_PROJECT

{
  terraform output -json | \
    jq -r 'keys[] as $k | "\($k) \(.[$k].value)"'
} | while read name value; do
  echo "$value" > $outputs/$name
done
