#!/bin/bash

cp tfstate/* greenpeace/terraform/production
cd greenpeace/terraform/production
terraform init
terraform plan -target="$TARGET" -detailed-exitcode \
               -var datadog_provider_api_key=$DATADOG_API_KEY \
               -var datadog_provider_app_key=$DATADOG_APP_KEY \
               -var credentials="not-used-here"

exitcode=$?
if [ $exitcode -eq 0 ]; then
  echo "Succeeded, diff is empty (no changes)"
elif [ $exitcode -eq 2 ]; then
  echo "There is a diff, code must be updated"
  false
else
  echo "Errored"
  false
fi