#!/bin/bash

set -e -u

outputs=$PWD/outputs

deployment_path=ci/deployments/branch-env

cat > cloud-config/cloud-config.yml <<EOF
vm_extensions:
- name: ${WORKSPACE}-target-pool
  cloud_properties:
    target_pool: ${WORKSPACE}-target-pool
EOF

cd $deployment_path

echo "$GCP_KEY" > keys/gcp.json

terraform init

terraform workspace select "$WORKSPACE" || \
  terraform workspace new "$WORKSPACE"

terraform apply --auto-approve --var project=$GCP_PROJECT
