#!/bin/bash
# vim: set ft=sh

set -e -u

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

cd concourse

if [ -f .git/resource/changed_files ]; then
  grep -v release-notes .git/resource/changed_files || {
    echo 'skipping testing for release-notes-only change'
    exit 0
  }
fi

go mod download

go install github.com/onsi/ginkgo/ginkgo

ginkgo -r -nodes=4 -race -keepGoing -slowSpecThreshold=15 ./testflight "$@"
