#!/bin/bash
# vim: set ft=sh

set -e -u

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

cd concourse

go mod download

go install github.com/onsi/ginkgo/ginkgo

# CGO is required for go test -race
CGO_ENABLED=1 ginkgo -r -nodes=4 -race -keepGoing -slowSpecThreshold=15 -flakeAttempts=3 ./testflight "$@"
