#!/bin/bash
# vim: set ft=sh

set -e -u

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

cd concourse

if [ -f .git/resource/changed_files ]; then
  grep -v release-notes .git/resource/changed_files || {
    echo 'skipping testing for release-notes-only change'
    exit 0
  }
fi

mkdir /tmp/concourse-pg-runner
if ! mount -t tmpfs none /tmp/concourse-pg-runner 2>/dev/null; then
  if grep '/dev/shm.*tmpfs' /proc/mounts >/dev/null; then
    mkdir /dev/shm/concourse-pg-runner
    rmdir /tmp/concourse-pg-runner
    ln -s /dev/shm/concourse-pg-runner /tmp/concourse-pg-runner
  else
    echo 'failed to mount tmpfs for pg. this is OK, db suite will just be slow'
  fi
fi


go mod download

go install github.com/onsi/ginkgo/ginkgo

ginkgo -r -p -race -skipPackage testflight,topgun "$@"
