#!/bin/bash

set -e

tar -xzf concourse-tarball/concourse-*.tgz
cd concourse

./bin/concourse --version

tar -xzf fly-assets/fly-darwin-amd64.tgz
./fly --version

GODEBUG="netdns=1" ./fly -t dummy login -c http://example.com 2> fly_error || true
grep "using cgo DNS resolver" fly_error
