#!/bin/bash

set -e -u

PRNUMBER=$(cat concourse-pr/.git/resource/pr)

validator/release-me validate \
    --github-token=$GITHUB_TOKEN \
    --github-owner=concourse \
    --github-repo=concourse \
    --pr-number=$PRNUMBER \