#!/bin/bash

# vim: set ft=sh

set -e -u

readonly ATC_URL="${ATC_URL:-}"
readonly MAX_TICKS="${MAX_TICKS:-}"
readonly TARGET_NAME="wait-worker-"$RANDOM

main() {
  check_environment_variables
  create_target
  try_until_responding
}

check_environment_variables() {
  if [[ -z $ATC_URL ]]; then
    echo "ATC_URL environment variable must be specified"
    exit 1
  fi

  if [[ -z $ATC_ADMIN_USERNAME ]]; then
    echo "ATC_ADMIN_USERNAME environment variable must be specified"
    exit 1
  fi

  if [[ -z $ATC_ADMIN_PASSWORD ]]; then
    echo "ATC_ADMIN_PASSWORD environment variable must be specified"
    exit 1
  fi

  if [[ -z $MAX_TICKS ]]; then
    echo "MAX_TICKS environment variable must be specified"
    exit 1
  fi
}

create_target() {
  fly -t $TARGET_NAME login -c $ATC_URL -u $ATC_ADMIN_USERNAME -p $ATC_ADMIN_PASSWORD
}

try_until_responding() {
  echo "waiting for a worker to be running"

  for _ in $(seq 1 $MAX_TICKS); do
    if fly -t $TARGET_NAME workers | grep 'running' >/dev/null; then
      echo "worker started"
      exit 0
    fi
    echo -n '.'
    sleep 1
  done
  echo "giving up. :("
  exit 1
}

main
