#!/bin/bash
# vim: set ft=sh

set -e

cd concourse

if [ -f .git/resource/changed_files ]; then
  grep -v release-notes .git/resource/changed_files || {
    echo 'skipping testing for release-notes-only change'
    exit 0
  }
fi

# check if smoke tests already downloaded fly
if ! [ -e /usr/local/bin/fly ]; then
  go install ./fly
fi

cd web/wats

stty columns 80 # for better yarn output
yarn install

yarn test -v --color "$@"
