#!/bin/bash

set -e -u

source ci/tasks/scripts/docker-helpers.sh

start_docker

docker load -i dev-image/image.tar
docker load -i "$POSTGRES_IMAGE/image.tar"

# note: tag must take precedence, since the digest returned by the
# registry-image resource is not the same as the image id in the docker CLI.
# the oci-build-task, however, gives a digest that can be used
[ -f dev-image/digest ] && export CONCOURSE_DEV_IMAGE="$(cat dev-image/digest)"
[ -f dev-image/tag ] && export CONCOURSE_DEV_IMAGE="concourse/dev:$(cat dev-image/tag)"
export POSTGRES_TAG=$(cat "$POSTGRES_IMAGE/tag")
export CONCOURSE_KEYS=$PWD/keys

if [[ "$RUNTIME" = "containerd" && "$HAS_RUNTIME_FLAG" = "false" ]]; then
  DOCKER_COMPOSE_FLAGS="-f concourse/docker-compose.yml -f ci/overrides/docker-compose.ci-containerd-legacy.yml"
else
  DOCKER_COMPOSE_FLAGS="-f concourse/docker-compose.yml -f ci/overrides/docker-compose.ci-$RUNTIME.yml"
fi

ci/tasks/scripts/generate-keys

docker-compose \
  $DOCKER_COMPOSE_FLAGS \
  -f ci/overrides/docker-compose.no-build.yml \
  up --no-build -d

trap stop_docker_compose EXIT SIGTERM SIGINT
function stop_docker_compose() {
  docker-compose -f concourse/docker-compose.yml logs > docker-compose.log
  docker-compose -f concourse/docker-compose.yml down
  stop_docker
}

apt-get install net-tools curl
cat /etc/os-release
ps -wwef
netstat -at

"$@"
