#!/bin/bash

set -e -u

source ci/tasks/scripts/docker-helpers.sh

start_docker

[ -d dev-image ] && docker load -i dev-image/image.tar
[ -d postgres-image ] && docker load -i postgres-image/image.tar

export CONCOURSE_DEV_TAG=$(cat dev-image/tag)
export POSTGRES_TAG=$(cat postgres-image/tag)
export CONCOURSE_KEYS=$PWD/keys

DOCKER_COMPOSE_FLAGS="-f concourse/docker-compose.yml -f ci/overrides/docker-compose.ci.yml"

if [ "$CONTAINERD" = "true" ]; then
  DOCKER_COMPOSE_FLAGS="$DOCKER_COMPOSE_FLAGS -f concourse/hack/overrides/containerd.yml"
fi

if [ "$BUILD" = "true" ]; then
  docker-compose \
    $DOCKER_COMPOSE_FLAGS \
    up --build -d
else
  ci/tasks/scripts/generate-keys

  docker-compose \
    $DOCKER_COMPOSE_FLAGS \
    -f ci/overrides/docker-compose.no-build.yml \
    up --no-build -d
fi

trap stop_docker_compose EXIT SIGTERM SIGINT
function stop_docker_compose() {
  docker-compose -f concourse/docker-compose.yml logs > docker-compose.log
  docker-compose -f concourse/docker-compose.yml down
  stop_docker
}

"$@"
