#!/bin/bash
# vim: set ft=sh

set -e -u

# for better yarn output
stty columns 80

pushd concourse
  yarn install

  # Some weird networking stuff going on with hetzner hosted workers. Running
  # this command multiple times works around the network issues. Possibly related to IPv6
  set +e
  yarn build
  yarn build
  yarn build
  yarn build
  yarn build
  set -e
popd

cp -a ./concourse/. ./built-concourse
