---
platform: linux

image_resource:
  type: registry-image
  source: { repository: cgr.dev/chainguard/wolfi-base }

params:
  ADMIN_USERNAME:
  ADMIN_PASSWORD:
  CONCOURSE_URL:

inputs:
  - name: pipelines-and-tasks
  - name: teams

run:
  path: pipelines-and-tasks/tasks/reconfigure-teams/run.sh
