platform: linux

inputs:
  - name: ci
  - name: repo

outputs:
  - name: repo

run:
  path: sh
  args:
    - -c
    - |
      apk add --no-progress --no-cache bash git go
      ci/tasks/go-dependency-update/run.sh
