---
platform: linux

inputs:
- name: concourse
- name: ci
- name: final-version
  optional: true

outputs:
- name: fly

params:
  PLATFORM: ""
  ARCH: ""

caches:
- path: gopath

run:
  path: ci/tasks/fly-build/run.sh
