---
platform: linux

inputs:
  - name: concourse
  - name: ci
  - name: final-version
    optional: true

params:
  PLATFORM:
  ARCH:

outputs:
  - name: fly

caches:
  - path: gopath

run:
  path: ci/tasks/fly-build/run.sh
