---
platform: linux

inputs:
  - name: concourse
  - name: ci
  - name: final-version
    optional: true

outputs:
  - name: fly-builds

caches:
  - path: gopath

params:
  PLATFORMS:

run:
  path: ci/tasks/fly-build/run.sh
