platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

outputs:
- name: stemcell-version

params:
  STEMCELL_VERSION: ~
  CONCOURSE_VERSION: ~

run:
  path: /bin/bash
  args:
    - -cex
    - |
      echo $STEMCELL_VERSION > ./stemcell-version/stemcell-version-${CONCOURSE_VERSION}.txt
