#!/bin/bash

set -e -u

if [ "$#" != "1" ]; then
  echo "usage: $0 <path/to/concourse-chart>"
  exit 1
fi

concourse_chart=$1

grep -REhv '\s+#\s+' $concourse_chart/templates |
  grep -Eoh 'name: (([A-Z0-9_])+|http_proxy|https_proxy|no_proxy)' |
  sed -e "s/^name: //"
