---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

inputs:
- name: concourse
- name: ci
- name: dev-image
- name: concourse-image
  optional: true
- name: postgres-image
  optional: true
- name: vault-image
  optional: true

caches:
- path: gopath

run:
  path: ci/tasks/integration/run.sh
