#!/bin/bash

set -e -u

docker run -v ${CONCOURSE_KEYS}:/keys ${CONCOURSE_DEV_IMAGE} generate-key -t rsa -b 1024 -f /keys/session_signing_key
docker run -v ${CONCOURSE_KEYS}:/keys ${CONCOURSE_DEV_IMAGE} generate-key -t ssh -b 1024 -f /keys/tsa_host_key
docker run -v ${CONCOURSE_KEYS}:/keys ${CONCOURSE_DEV_IMAGE} generate-key -t ssh -b 1024 -f /keys/worker_key

cp keys/worker_key.pub keys/authorized_worker_keys
