#!/bin/bash

set -ex -u

source ci/tasks/helpers/docker-helpers.sh

start_docker

# load in concourse/concourse-dev:latest
[ -d concourse-rc-image ] && docker load -i concourse-rc-image/image.tar

docker compose -f docs/docker-compose.yml -f ci/overrides/docker-compose.latest-rc.yml up -d

# now run the watjs/smoke tests
export ATC_URL="http://localhost:8080"
export ATC_ADMIN_USERNAME="test"
export ATC_ADMIN_PASSWORD="test"

ci/tasks/watsjs-smoke/run.sh

pushd docs
  docker compose down
popd

stop_docker
