---
platform: linux

image_resource:
  type: registry-image
  source: { repository: cgr.dev/chainguard/wolfi-base }

inputs:
  - name: ci
  - name: concourse-tarball

run:
  path: ci/tasks/validate-linux-rc/run.sh
